apiVersion: v1
kind: Service
metadata:
  name: tis-console-loadbalancer
spec:
  ports:
    - port: 8080
      name: tis-console-8080
      protocol: TCP
      targetPort: tis-8080
  selector:
    app: tis-console
  type: LoadBalancer
---

#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv-oss
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteMany
#  storageClassName: oss
#  flexVolume:
#    driver: "alicloud/oss"
#    options:
#      bucket: "incr-log"
#      url: "oss-cn-hangzhou.aliyuncs.com"
#      path: "/tis-pv"
#      akId: ""
#      akSecret: ""
#      otherOpts: "-o max_stat_cache_size=0 -o allow_other"
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: tis-console-pvc-oss
#spec:
#  storageClassName: oss
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi

apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-pv
  labels:
    alicloud-pvname: disk-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: diskplugin.csi.alibabacloud.com
    volumeHandle: "d-bp15tdr3q90sxxz2l0dz"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.diskplugin.csi.alibabacloud.com/zone
              operator: In
              values:
                - "cn-hangzhou-k"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      alicloud-pvname: disk-pv

---
# how to use aliyun pv: https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/mount-a-statically-provisioned-oss-volume?spm=a2c4g.11186623.0.0.39145057wGt7rB
# 使用 云盘：https://help.aliyun.com/zh/ack/ack-managed-and-ack-dedicated/user-guide/use-a-statically-provisioned-disk-volume?spm=a2c4g.11186623.0.i5
apiVersion: v1
kind: ReplicationController
metadata:
  name: tis-console
spec:
  replicas: 1
  selector:
    app: tis-console
  template:
    metadata:
      labels:
        app: tis-console
    spec:
      containers:
        - name: tis-console
          volumeMounts:
            - name: tis-console-pvc
              mountPath: "/opt/data"
          image: registry.cn-hangzhou.aliyuncs.com/tis/tis-console:4.0.0
          ports:
            - name: tis-8080
              containerPort: 8080
      volumes:
        - name: tis-console-pvc
          persistentVolumeClaim:
            claimName: disk-pvc
---

