apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: TZ
          value: "Asia/Shanghai"
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql-3306
          protocol: TCP
        resources:
          requests:
            cpu: "2"
            memory: 4Gi
      terminationGracePeriodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - name: mysql-svc
      nodePort: 32005
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer

